### **Areawa Data Science Academy**
**Deep Learning Cohort 2.0**
Name: Mustapha Abdulkadir Sani
Email: mustapha.abdulkadir2205@gmail.com
Title: Week 1 Solution

Exercises Solution

1. Documentation Reading

**The documentation on torch.Tensor**
After reading the documentation I understood that tensors are used for representing the data that we want our model to manipulate  and learn from. If we are going to be working on images we have represent our images in form of tensors before PyTorch can actually process them. Tensor are just Multi dimensional matrices whose values represent our data. Tensor can store different data types ranging from float16, float32 etc.

**The documentation on torch.cuda**
torch.cuda is a package that allows us to work with GPUs to enable faster compuatation and parallelization. It has so many APIs one of which is is_available that can be use to determine if system one is using supports CUDA.

In [ ]:
# Question 2
# Creating a random tensor with shape (7,7)

# to create a random PyTorch tensor we need to import torch first
import torch
random_tensor=torch.rand(7,7) # create a random tensor of shape (7,7) and store it in a variable named random_tensor

# printing the created tensor on the screen
random_tensor



tensor([[0.9711, 0.4197, 0.0587, 0.0176, 0.0201, 0.0335, 0.3341],
        [0.4273, 0.9016, 0.2337, 0.8654, 0.2293, 0.3508, 0.6343],
        [0.4725, 0.8710, 0.0986, 0.6112, 0.6987, 0.8487, 0.9904],
        [0.6050, 0.3251, 0.2321, 0.7638, 0.6632, 0.4156, 0.5510],
        [0.6012, 0.1955, 0.9189, 0.7791, 0.9745, 0.1347, 0.2492],
        [0.0785, 0.5418, 0.3529, 0.5361, 0.6405, 0.5086, 0.4987],
        [0.8029, 0.4984, 0.9596, 0.9282, 0.3997, 0.6822, 0.3659]])

In [ ]:
# Question 3
# Performing matrix multiplication on the tensor created above
# with another random tensor with sgape (1,7)

# creating the second random tensor
random_tensor_2=torch.rand(1,7) # create a random tensor of shape (1,7) and store it in a variable named random_tensor_2

# printing the two tensor on the screen
print("First Tensor: ")
print(random_tensor)
print("Second Tensor: ")
print(random_tensor_2)

# performing the multiplication on the two random tensors
tensors_product=torch.matmul(random_tensor,random_tensor_2.T) # random_tensor_2 need to be transposed so that the dimension will match
# printing the result of the multiplication
print("Product of the two tensors: ")
print(tensors_product)


First Tensor: 
tensor([[0.9711, 0.4197, 0.0587, 0.0176, 0.0201, 0.0335, 0.3341],
        [0.4273, 0.9016, 0.2337, 0.8654, 0.2293, 0.3508, 0.6343],
        [0.4725, 0.8710, 0.0986, 0.6112, 0.6987, 0.8487, 0.9904],
        [0.6050, 0.3251, 0.2321, 0.7638, 0.6632, 0.4156, 0.5510],
        [0.6012, 0.1955, 0.9189, 0.7791, 0.9745, 0.1347, 0.2492],
        [0.0785, 0.5418, 0.3529, 0.5361, 0.6405, 0.5086, 0.4987],
        [0.8029, 0.4984, 0.9596, 0.9282, 0.3997, 0.6822, 0.3659]])
Second Tensor: 
tensor([[0.5494, 0.3506, 0.1450, 0.3120, 0.4909, 0.3824, 0.3210]])
Product of the two tensors: 
tensor([[0.8246],
        [1.3050],
        [1.7554],
        [1.3797],
        [1.3851],
        [1.1205],
        [1.6191]])


In [ ]:
# Question 4. Setting different random seeds

# 1. setting random seed 0

# setting the manual seed
torch.manual_seed(0)

# creating the two tensors
random_tensor_3=torch.rand(7,7)
random_tensor_4=torch.rand(1,7)

# printing the two tensors
print("First Tensor: ")
print(random_tensor_3)
print("Second Tensor: ")
print(random_tensor_4)

# performimg the matrix multiplication using random seed 0
random_seed_0_output=torch.matmul(random_tensor_3,random_tensor_4.T)
print("Product of the two tensors: ")
print(random_seed_0_output)

First Tensor: 
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Second Tensor: 
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
Product of the two tensors: 
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [ ]:
# 2. setting random seed 2

# setting the manual seed
torch.manual_seed(2)

# creating the two tensors
random_tensor_3=torch.rand(7,7)
random_tensor_4=torch.rand(1,7)

# printing the two tensors
print("First Tensor: ")
print(random_tensor_3)
print("Second Tensor: ")
print(random_tensor_4)

# performimg the matrix multiplication using random seed 0
random_seed_2_output=torch.matmul(random_tensor_3,random_tensor_4.T)
print("Product of the two tensors: ")
print(random_seed_2_output)

First Tensor: 
tensor([[0.6147, 0.3810, 0.6371, 0.4745, 0.7136, 0.6190, 0.4425],
        [0.0958, 0.6142, 0.0573, 0.5657, 0.5332, 0.3901, 0.9088],
        [0.5334, 0.7073, 0.7116, 0.2050, 0.3078, 0.9809, 0.0103],
        [0.4660, 0.4604, 0.8547, 0.4525, 0.6317, 0.4760, 0.2200],
        [0.2166, 0.2571, 0.0458, 0.1755, 0.6177, 0.8291, 0.5246],
        [0.2708, 0.7197, 0.3081, 0.3892, 0.2259, 0.3430, 0.0367],
        [0.7133, 0.6944, 0.5993, 0.7455, 0.7119, 0.5221, 0.5530]])
Second Tensor: 
tensor([[0.5382, 0.7668, 0.8359, 0.8591, 0.7898, 0.3781, 0.4777]])
Product of the two tensors: 
tensor([[2.5722],
        [2.0592],
        [2.2192],
        [2.4909],
        [1.5547],
        [1.6152],
        [3.0816]])


In [ ]:
# 1. setting random seed 3

# setting the manual seed
torch.manual_seed(3)

# creating the two tensors
random_tensor_3=torch.rand(7,7)
random_tensor_4=torch.rand(1,7)

# printing the two tensors
print("First Tensor: ")
print(random_tensor_3)
print("Second Tensor: ")
print(random_tensor_4)

# performimg the matrix multiplication using random seed 0
random_seed_3_output=torch.matmul(random_tensor_3,random_tensor_4.T)
print("Product of the two tensors: ")
print(random_seed_3_output)

First Tensor: 
tensor([[0.0043, 0.1056, 0.2858, 0.0270, 0.4716, 0.0601, 0.7719],
        [0.7437, 0.5944, 0.8879, 0.4510, 0.7995, 0.1498, 0.4015],
        [0.0542, 0.4594, 0.1756, 0.9492, 0.8473, 0.8749, 0.6483],
        [0.2148, 0.9493, 0.0121, 0.1809, 0.1877, 0.2927, 0.5997],
        [0.1213, 0.1148, 0.2609, 0.8052, 0.1394, 0.0516, 0.0666],
        [0.2540, 0.3686, 0.0043, 0.2659, 0.5096, 0.5824, 0.4283],
        [0.4433, 0.1747, 0.7562, 0.3795, 0.1581, 0.3796, 0.4301]])
Second Tensor: 
tensor([[0.9623, 0.7606, 0.2981, 0.4291, 0.9418, 0.8212, 0.6247]])
Product of the two tensors: 
tensor([[1.1569],
        [2.7528],
        [2.7826],
        [1.8017],
        [0.8425],
        [1.8660],
        [1.6771]])


In [ ]:
# Examining and comparing the output of different random seeds
print("Output of random seed 0: ")
print(random_seed_0_output)
print("Output of random seed 2: ")
print(random_seed_2_output)
print("Output of random seed 3: ")
print(random_seed_3_output)

Output of random seed 0: 
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
Output of random seed 2: 
tensor([[2.5722],
        [2.0592],
        [2.2192],
        [2.4909],
        [1.5547],
        [1.6152],
        [3.0816]])
Output of random seed 3: 
tensor([[1.1569],
        [2.7528],
        [2.7826],
        [1.8017],
        [0.8425],
        [1.8660],
        [1.6771]])


In [ ]:
# Question 5: Setting GPU equivalent of torch.manual_seed
# After checking the documentation, I found that it actually exist

# set random seed for GPU using 1234
torch.cuda.manual_seed(1234)

In [ ]:
# Question 6: creating two random tensors and sending them to GPU

# To achieve this, I have to change my run time type by switching from CPU to GPU
# I also need to set device agnostic code

# setting random seed
torch.manual_seed(1234)

# setting device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"

# check for access to GPU
print(f"Device: {device}")

# creating the two tensors
random_tensor_5=torch.rand(2,3).to("cuda") # to("cuda") means we are sending the tensor to GPU
random_tensor_6=torch.rand(2,3).to("cuda")

# printing the two newly created te tensors
print("First Tensor on GPU: ")
print(random_tensor_5)
print("Second Tensor on GPU: ")
print(random_tensor_6)


Device: cuda
First Tensor on GPU: 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Second Tensor on GPU: 
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [ ]:
# Question 7: Performing matrix multiplication on the tensors created in 6 above

# perform matrix multiplication on random_tensor_5 and random_tensor_6
question_7_output=torch.matmul(random_tensor_5,random_tensor_6.T) # need to transpose one of the tesnors, so that the dimension will match

# print the result of the multiplication
print(question_7_output)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [ ]:
# Question 8: Finding the maximum and minimum values of question 7 output

# finding the max value
max_value=torch.max(question_7_output)

# finding the min value
min_value=torch.min(question_7_output)

# printing the max and min values
print(f"Max value: {max_value}")
print(f"Min value: {min_value}")


Max value: 0.5617256760597229
Min value: 0.3647301495075226


In [ ]:
# Question 8: Finding the maximum and minimum in dex values of question 7 output

# finding the max value
max_index_value=torch.argmax(question_7_output)

# finding the min value
min_index_value=torch.argmin(question_7_output)

# printing the max and min index values
print(f"Max value: {max_index_value}")
print(f"Min value: {min_index_value}")


Max value: 3
Min value: 0


In [ ]:
# Question 10: Creating a tensor with shape (1,,1,1,10)
# and then create a new tensor with all 1 dimension removes, and setting seed to 7

# setting the seed
torch.manual_seed(7)

# creating the tensor
tensor_10=torch.rand(1,1,1,10)

# printing the tensor
print(tensor_10)
print(f"Tensor shape: {tensor_10.shape}")

# removing the 1s dimension
tensor_10_squeezed=tensor_10.squeeze() # the squeeze() method removes the 1s dimensions

# printing the new tensor
print(tensor_10_squeezed)
print(f"Tensor shape: {tensor_10_squeezed.shape}")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor shape: torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Tensor shape: torch.Size([10])
